select * from employees;
SELECT COUNT(*) AS Total_Records FROM employees;
SELECT * FROM employees WHERE Age IS NULL OR Department IS NULL OR MonthlyIncome IS NULL OR Attrition IS NULL;
SELECT EmployeeNumber, COUNT(*) AS Duplicate_Count FROM employees GROUP BY EmployeeNumber HAVING COUNT(*) > 1;
SELECT * FROM employees WHERE EmployeeNumber IN (2060, 2064, 2054, 2057, 2068) ORDER BY EmployeeNumber;
describe employees;
CREATE TABLE employees_clean AS SELECT DISTINCT * FROM employees;
SELECT COUNT(*) FROM employees;
SELECT COUNT(*) FROM employees_clean;
SELECT * FROM employees_clean LIMIT 10;
DROP TABLE employees; 
RENAME TABLE employees_clean TO employees;
SELECT COUNT(*) FROM employees;
SELECT DISTINCT Department FROM employees;
SELECT DISTINCT JobRole FROM employees;
SELECT DISTINCT Attrition FROM employees;
SELECT DISTINCT Gender FROM employees;
select count(*) AS total_employees FROM employees;
SELECT Department, COUNT(*) AS Total_Employees FROM employees GROUP BY Department;
SELECT Department, AVG(MonthlyIncome) AS Avg_Salary FROM employees GROUP BY department;
SELECT Attrition, COUNT(*) AS Employee_Count FROM employees GROUP BY Attrition;
SELECT Department, AVG(Age) AS Avg_Age FROM employees GROUP BY department;
SELECT EmployeeNumber, MonthlyIncome FROM employees ORDER BY MonthlyIncome DESC LIMIT 10;
SELECT BusinessTravel, Count(*) AS Total_Employee FROM employees GROUP BY BusinessTravel;
SELECT JobRole, COUNT(*) AS Total_Employees FROM employees GROUP BY JobRole ORDER BY Total_Employees DESC;
SELECT JobRole, AVG(MonthlyIncome) AS Avg_Income FROM employees GROUP BY JobRole ORDER BY Avg_Income DESC;
SELECT Department, Attrition, COUNT(*) AS Employee_Count FROM employees GROUP BY Department, Attrition ORDER BY Department;
SELECT EmployeeNumber, JobRole, Department, MonthlyIncome FROM employees ORDER BY MonthlyIncome DESC LIMIT 10;
SELECT EmployeeNumber, Department, JobRole, MonthlyIncome FROM employees WHERE MonthlyIncome > (SELECT AVG(MonthlyIncome) FROM employees);
SELECT Department, JobRole, EmployeeNumber, MonthlyIncome FROM (SELECT *, ROW_NUMBER() OVER ( PARTITION BY Department ORDER BY MonthlyIncome DESC ) AS rn FROM employees) t WHERE rn <= 3;
SELECT Department, AVG(JobSatisfaction) AS Avg_Job_Satisfaction FROM employees GROUP BY Department;
SELECT Department, COUNT(CASE WHEN Attrition='Yes' THEN 1 END) AS Attrition_Count, COUNT(*) AS Total_Employees FROM employees GROUP BY Department;
SELECT Department, AVG(MonthlyIncome) AS Avg_Salary FROM employees GROUP BY Department ORDER BY Avg_Salary DESC;
SELECT EmployeeNumber, JobRole, Department, JobSatisfaction FROM employees WHERE JobSatisfaction >= 4;
SELECT Department, AVG(YearsAtCompany) AS Avg_Years FROM employees GROUP BY Department;
SELECT OverTime, COUNT(*) AS Employees FROM employees GROUP BY OverTime;
